def inverse_byte(value: int) -> int: ...
def inverse_word(value: int) -> int: ...
def inverse_dword(value: int) -> int: ...
def inverse_qword(value: int) -> int: ...
def inverse_bytes(value: bytes) -> bytes: ...
